In [16]:
import pyarrow
from helper import *

I moved classes and functions from the previous notebook to the `helper.py` not to rewrite the same code

In [2]:
HR_train_paths = sorted(glob.glob("../data/DIV2K_train_HR/*.png"))
X2_train_paths = sorted(glob.glob("../data/DIV2K_train_LR_bicubic/X2/*.png"))
X4_train_paths = sorted(glob.glob("../data/DIV2K_train_LR_bicubic/X4/*.png"))
X8_train_paths = sorted(glob.glob("../data/DIV2K_train_LR_bicubic/X8/*.png"))
X16_train_paths = sorted(glob.glob("../data/DIV2K_train_LR_bicubic/X16/*.png"))
X32_train_paths = sorted(glob.glob("../data/DIV2K_train_LR_bicubic/X32/*.png"))
X64_train_paths = sorted(glob.glob("../data/DIV2K_train_LR_bicubic/X64/*.png"))

HR_valid_paths = sorted(glob.glob("../data/DIV2K_valid_HR/*.png"))
X2_valid_paths = sorted(glob.glob("../data/DIV2K_valid_LR_bicubic/X2/*.png"))
X4_valid_paths = sorted(glob.glob("../data/DIV2K_valid_LR_bicubic/X4/*.png"))
X8_valid_paths = sorted(glob.glob("../data/DIV2K_valid_LR_bicubic/X8/*.png"))
X16_valid_paths = sorted(glob.glob("../data/DIV2K_valid_LR_bicubic/X16/*.png"))
X32_valid_paths = sorted(glob.glob("../data/DIV2K_valid_LR_bicubic/X32/*.png"))
X64_valid_paths = sorted(glob.glob("../data/DIV2K_valid_LR_bicubic/X64/*.png"))

## Final Results

### X2 Scaling

In [3]:
checkpoint = torch.load('../model_checkpoints/SRResNet/X2.pth')
model = SRResNet(2).to(device)
model.load_state_dict(checkpoint['model_state_dict'])

In [4]:
model.eval();

In [5]:
targets = [X32_valid_paths, X16_valid_paths, X8_valid_paths, X4_valid_paths, X2_valid_paths, HR_valid_paths]

metrics_x2 = pd.DataFrame(columns=["PSNR↑", "SSIM↑", "LPIPS↓"])
for target_ds in tqdm(targets, total=6):
    metrics_x2.loc[len(metrics_x2)] = calc_metrics(model, target_ds, 2)

metrics_x2.index = [
    "31px -> 62px", "63px -> 126px", "127px -> 254px", 
    "255px -> 510px", "510px -> 1020px", "1020px -> 2040px"
]
metrics_x2

  0%|          | 0/6 [00:00<?, ?it/s]

  0%|          | 0/100 [00:00<?, ?it/s]

  0%|          | 0/100 [00:00<?, ?it/s]

  0%|          | 0/100 [00:00<?, ?it/s]

  0%|          | 0/100 [00:00<?, ?it/s]

  0%|          | 0/100 [00:00<?, ?it/s]

  0%|          | 0/100 [00:00<?, ?it/s]

                      PSNR↑     SSIM↑    LPIPS↓
31px -> 62px      26.662233  0.879098  0.054308
63px -> 126px     27.917544  0.895056  0.080245
127px -> 254px    29.730202  0.917923  0.081397
255px -> 510px    31.295589  0.927820  0.079176
510px -> 1020px   33.236746  0.938645  0.077401
1020px -> 2040px  34.531631  0.936807  0.090742

### X4 Scaling

In [7]:
checkpoint = torch.load('../model_checkpoints/SRResNet/X4.pth')
model = SRResNet(4).to(device)
model.load_state_dict(checkpoint['model_state_dict'])

In [8]:
model.eval();

In [9]:
targets = [X16_valid_paths, X8_valid_paths, X4_valid_paths, X2_valid_paths, HR_valid_paths]

metrics_x4 = pd.DataFrame(columns=["PSNR↑", "SSIM↑", "LPIPS↓"])
for target_ds in tqdm(targets, total=5):
    metrics_x4.loc[len(metrics_x4)] = calc_metrics(model, target_ds, 4)

metrics_x4.index = [
    "31px -> 124px", "63px -> 252px", "127px -> 508px", 
    "255px -> 1020px", "510px -> 2040px"
]
metrics_x4

  0%|          | 0/5 [00:00<?, ?it/s]

  0%|          | 0/100 [00:00<?, ?it/s]

  0%|          | 0/100 [00:00<?, ?it/s]

  0%|          | 0/100 [00:00<?, ?it/s]

  0%|          | 0/100 [00:00<?, ?it/s]

  0%|          | 0/100 [00:00<?, ?it/s]

                     PSNR↑     SSIM↑    LPIPS↓
31px -> 124px    22.624891  0.667312  0.332162
63px -> 252px    23.985385  0.716185  0.312878
127px -> 508px   25.493296  0.760469  0.282658
255px -> 1020px  27.351784  0.798972  0.261175
510px -> 2040px  28.854268  0.816150  0.278362

### X8 Scaling

In [10]:
checkpoint = torch.load('../model_checkpoints/SRResNet/X8.pth')
model = SRResNet(8).to(device)
model.load_state_dict(checkpoint['model_state_dict'])

In [11]:
model.eval();

In [12]:
targets = [X8_valid_paths, X4_valid_paths, X2_valid_paths, HR_valid_paths]

metrics_x8 = pd.DataFrame(columns=["PSNR↑", "SSIM↑", "LPIPS↓"])
for target_ds in tqdm(targets, total=4):
    metrics_x8.loc[len(metrics_x8)] = calc_metrics(model, target_ds, 8)

metrics_x8.index = ["31px -> 248px", "63px -> 504px", "127px -> 1016px", "255px -> 2040px"]
metrics_x8

  0%|          | 0/4 [00:00<?, ?it/s]

  0%|          | 0/100 [00:00<?, ?it/s]

  0%|          | 0/100 [00:00<?, ?it/s]

  0%|          | 0/100 [00:00<?, ?it/s]

  0%|          | 0/100 [00:00<?, ?it/s]

                     PSNR↑     SSIM↑    LPIPS↓
31px -> 248px    20.770887  0.511819  0.539054
63px -> 504px    22.038205  0.575173  0.495814
127px -> 1016px  23.698920  0.643392  0.450260
255px -> 2040px  25.312492  0.687486  0.441936

### Summary

In [13]:
index_x2 = pd.MultiIndex.from_product([["X2"], [
    "31px -> 62px", "63px -> 126px", "127px -> 254px", 
    "255px -> 510px", "510px -> 1020px", "1020px -> 2040px"
]], names=["Scaling", "Resolution"])

index_x4 = pd.MultiIndex.from_product([["X4"], [
    "31px -> 124px", "63px -> 252px", "127px -> 508px", 
    "255px -> 1020px", "510px -> 2040px"
]], names=["Scaling", "Resolution"])

index_x8 = pd.MultiIndex.from_product([["X8"], [
    "31px -> 248px", "63px -> 504px", "127px -> 1016px", "255px -> 2040px"]], names=["Scaling", "Resolution"])

metrics_x2.index = index_x2
metrics_x4.index = index_x4
metrics_x8.index = index_x8

empty_row = pd.DataFrame([[np.nan, np.nan, np.nan]], columns=["PSNR↑", "SSIM↑", "LPIPS↓"], 
                         index = pd.MultiIndex.from_tuples([("--", "--")], names=["Scaling", "Resolution"]))
metrics_full = pd.concat([metrics_x2, empty_row, metrics_x4, empty_row, metrics_x8])
metrics_full

                              PSNR↑     SSIM↑    LPIPS↓
Scaling Resolution
X2      31px -> 62px      26.662233  0.879098  0.054308
        63px -> 126px     27.917544  0.895056  0.080245
        127px -> 254px    29.730202  0.917923  0.081397
        255px -> 510px    31.295589  0.927820  0.079176
        510px -> 1020px   33.236746  0.938645  0.077401
        1020px -> 2040px  34.531631  0.936807  0.090742
--      --                      NaN       NaN       NaN
X4      31px -> 124px     22.624891  0.667312  0.332162
        63px -> 252px     23.985385  0.716185  0.312878
        127px -> 508px    25.493296  0.760469  0.282658
        255px -> 1020px   27.351784  0.798972  0.261175
        510px -> 2040px   28.854268  0.816150  0.278362
--      --                      NaN       NaN       NaN
X8      31px -> 248px     20.770887  0.511819  0.539054
        63px -> 504px     22.038205  0.575173  0.495814
        127px -> 1016px   23.698920  0.643392  0.450260
        255px -> 2040px   25.312492  0.687486  0.441936

### Save the results for later comparison

In [17]:
os.makedirs('../metrics_results', exist_ok=True)
metrics_full.to_parquet("../metrics_results/SRResNet.parquet", engine="pyarrow")

In [18]:
df = pd.read_parquet("../metrics_results/SRResNet.parquet")
df

                              PSNR↑     SSIM↑    LPIPS↓
Scaling Resolution
X2      31px -> 62px      26.662233  0.879098  0.054308
        63px -> 126px     27.917544  0.895056  0.080245
        127px -> 254px    29.730202  0.917923  0.081397
        255px -> 510px    31.295589  0.927820  0.079176
        510px -> 1020px   33.236746  0.938645  0.077401
        1020px -> 2040px  34.531631  0.936807  0.090742
--      --                      NaN       NaN       NaN
X4      31px -> 124px     22.624891  0.667312  0.332162
        63px -> 252px     23.985385  0.716185  0.312878
        127px -> 508px    25.493296  0.760469  0.282658
        255px -> 1020px   27.351784  0.798972  0.261175
        510px -> 2040px   28.854268  0.816150  0.278362
--      --                      NaN       NaN       NaN
X8      31px -> 248px     20.770887  0.511819  0.539054
        63px -> 504px     22.038205  0.575173  0.495814
        127px -> 1016px   23.698920  0.643392  0.450260
        255px -> 2040px   25.312492  0.687486  0.441936